### ISSUE TITLE
Basic homebrew formula for podman-machine

### ISSUE THREAD

**Issue by RothAndrew** [ttu-capstone-podman/homebrew-podman-machine#5]
Story:

As a user of homebrew-podman-machine, I would like to install podman-machine on MacOS using homebrew.

Accpetance Criteria:

1. Given all dependencies (like VirtualBox) are installed, `brew install ttu-capstone-podman/podman-machine` installs podman-machine.
1. `podman-machine` is present in $PATH after installing
1. `podman-machine --version` returns successfully.

Notes:

1. Homebrew has a command that bootstraps a new tap called `brew new-tap`. It created the folder structure and `acure-pipelines.yml`. I went ahead and set up CI through Azure Pipelines and CodeFactor
1. The Azure pipeline has to be manually triggered by typing `/azp run` in the MR. If it doesn't work, change your visibility on https://github.com/orgs/ttu-capstone-podman/people from private to public.
1. Do the least amount of work possible to get the acceptance criteria completed. Do not install dependencies automatically.

**Comment by Jmwhite45** [comment]
https://docs.brew.sh/Formula-Cookbook
